changed stub endpoints to distinguish between GB and NI
hmrc/transits-movements-trader-at-departure-stub pull request #24
Opened 2021-01-13 19:05 UTC by RobertLaverick

2021-01-14 08:58 UTC, crystalmark approved these changes

2021-01-14 13:16 UTC, crystalmark approved these changes

2021-01-14 16:05 UTC, amaalali requested changes
The context of this is to validate the bearer token headers. Is this a thing that should be done in this service? This is a stub service and it is usually advised that stubs have minimal logic

For the 2 different endpoints, I don't think we should have a separate controller methods since the original method had the functionality for both gb and ni (ignoring the above issue)

2021-01-14 16:09 UTC, amaalali commented on test/controllers/DeparturesControllerSpec.scala
> +      }
This is not the contract documented in the EIS spec

2021-01-15 09:01 UTC, crystalmark requested changes

2021-01-18 15:16 UTC, ashwinirudrappa approved these changes
@RobertLaverick Code looks good from a web point of view

2021-01-18 15:16 UTC, ashwinirudrappa commented on test/controllers/DeparturesControllerSpec.scala
> +      "should return 202 Accepted" in {
```suggestion
      "should return 400 BadRequest" in {
```
Please update the test description

2021-01-18 15:16 UTC, ashwinirudrappa commented on test/controllers/DeparturesControllerSpec.scala
> +      "should return 202 Accepted" in {
@RobertLaverick Please update the test description to return 400 instead of 202

2021-01-18 15:53 UTC, merged